
display:
  figsize: [4, 4]
  dpi: 128
  plot_options:
    color: [0.25, 0.25, 0.75]
    linewidth: 1
    merkersize: 1
    linstyle: "solid"
  fg_options:
    color: [0.55, 0.55, 0.9]
    markersize: 2

init: |
  import neuropythy as ny
  import numpy as np

  nsd_path = ny.util.pseudo_path('s3://natural-scenes-dataset/nsddata/',
                                 cache_path='/cache/nsd')
  nsd_prf_files = {"polar_angle": "prfangle.mgz",
                   "eccentricity": "prfeccentricity.mgz",
                   "cod": "prfR2.mgz"}
  occpole_mask = ('parcellation', 43)

targets:
  Subject ID:
    - subj01
    - subj02
    - subj03
    - subj04
    - subj05
    - subj06
    - subj07
    - subj08
  subject: |
    sid = target['Subject ID']
    return ny.freesurfer_subject(nsd_path.subpath('freesurfer', sid))
  Hemisphere:
    - LH
    - RH
  cortex: |
    sub = target['subject']
    h = target['Hemisphere'].lower()
    props = {k: sub.load('label', filename)
             for (k,filename) in nsd_prf_files.items()}
    cortex = sub.hemis[h]
    return cortex.with_prop(props)
  flatmap: |
    cortex = target['cortex']
    return cortex.mask_flatmap(occpole_mask, map_right='right', radius=np.pi/2)

annotations:
  Periphery:
    - ["polar_angle", "eccentricity"]
    - ["curvature", "cod"]
  V1 Boundary:
    - ["polar_angle", "eccentricity"]
    - ["curvature", "cod"]
  V2 Boundary:
    - ["polar_angle", "eccentricity"]
    - ["curvature", "cod"]
  V3 Boundary:
    - ["polar_angle", "eccentricity"]
    - ["curvature", "cod"]

figures:
  polar_angle: |
    ny.cortex_plot(target['flatmap'], color="polar_angle", axes=axes)
  eccentricity: |
    ny.cortex_plot(target['flatmap'], color="eccentricity", axes=axes)
  cod: |
    ny.cortex_plot(target['flatmap'], color="cod", axes=axes,
                   cmap='hot', vmin=0, vmax=100)
  curvature: |
    ny.cortex_plot(target['flatmap'], axes=axes)

    
    
